# Default values for fedlearner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

fedlearner-operator:
  image:
    repository: fedlearner/fedlearner-operator
    tag: "4b2f91a"
    pullPolicy: IfNotPresent

  ingress:
    enabled: true

  extraArgs: {}

fedlearner-apiserver:
  image:
    repository: fedlearner/fedlearner-apiserver
    tag: "4b2f91a"
    pullPolicy: IfNotPresent

fedlearner-web-console:
  image:
    repository: fedlearner/fedlearner-web-console
    tag: "4b2f91a"
    pullPolicy: IfNotPresent

  ingress:
    enabled: true
